name = "Regex"
version = "0.1.0"
keywords = ["regex"]
defaultTargets = ["Regex"]

[[lean_lib]]
name = "Regex"
buildType = "relWithDebInfo"

[[lean_exe]]
name = "Bench"
srcDir = "scripts"
buildType = "relWithDebInfo"
