name: continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
      name: Build
      strategy:
        fail-fast: false
        matrix:
          os:
            # lean-action does not provide lake executable on Windows for some reason
            # - windows-latest
            - ubuntu-latest
            - macos-latest
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v4
        - name: Build Regex
          uses: leanprover/lean-action@v1
          with:
            build-args: '--wfail'
            lake-package-directory: regex
        - name: Run CorpusTest
          run: |
            cd regex
            time lake exe CorpusTest --verify
            time lake exe CorpusTest --verify --backtracker
            time lake exe CorpusTest --verify --backtracker
            time lake exe CorpusTest --verify
        - name: Build RegexCorrectness
          uses: leanprover/lean-action@v1
          with:
            build-args: '--wfail'
            lake-package-directory: correctness
        - name: Build docs
          working-directory: docbuild
          run: lake build --keep-toolchain Regex:docs RegexCorrectness:docs
